### ISSUE TITLE
When I use Kashacter Admin commands say access denied

### ISSUE THREAD

**Issue by GatorTank2123** [S-ESX/S-ESX-V1F#7]
Any one have this issue been messing with it for awhile, I set my group to admin in the database as well! Makes no sense!

**Comment by schwim0341** [comment]
Did you set yourself as admin in server.cfg as well?

**Comment by GatorTank2123** [comment]
this is how my admin in cfg is setup
# Add system admins
add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit
group.admin 
## ESX ADD ##
add_principal group.admin group.user
add_ace resource.es_extended command.add_ace allow
add_ace resource.es_extended command.add_principal allow
add_ace resource.es_extended command.remove_principal allow
add_ace resource.es_extended command.stop allow
## END ESX ADD ##

**Comment by schwim0341** [comment]
I could be wrong but that fivem Id changes. Is there a reason you're not using license or steam?

**Comment by GatorTank2123** [comment]
Your awesome!!!!!! No there was no reason I thought fivem was license like a dummy, I'm still new to all this, learning one mistake at a time! 3 days of my life for one word hahah I can't thank you enough!!!
